src/smexperiments/trial.py
src/smexperiments/trial_component.py
tests/integ-jobs/test_track_from_training_job.py
tests/unit/test_list_trial_components_from_trial.py
tests/unit/test_trial_component.py

add a method on trial object to list related trial components
add trial name and experiment name filter parameters to list trial components method
```
tests/integ/test_experiment.py .......                                                                                                                                                             [  7%]
tests/integ/test_tracker.py .......                                                                                                                                                                [ 14%]
tests/integ/test_trial.py .....                                                                                                                                                                    [ 19%]
tests/integ/test_trial_component.py .... …
```

add list trial components method on trial object and trial/experiment name filter params

---

.github/workflows/main.yml
setup.py

run tests on pull request

---

tests/conftest.py
tests/integ-jobs/docker/Dockerfile
tests/integ-jobs/test_track_from_training_job.py

make boto model file optional

---

src/smexperiments/_utils.py
src/smexperiments/metrics.py

* remove basicConfig to allow customers to use their own logging mechanisms
* add additional logging statements

more consistent logging

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

add additional contribution information

add additional contribution information

---

README.rst

add several more badges

---

src/smexperiments/trial_component.py

add description of create Trial Component behavior

add description of create Trial Component behavior

---

.github/workflows/build_release.yml
README.rst

remove duplicate docs badge

---

setup.py

we have docker dependency in tox.ini, but missing it in setup.py.
added missing dependency.
Github Action workflow run successfully

add missing test dependencies for setup.py

---

README.rst

add notebook badge to easily launch example notebook

add notebook badge

---

tox.ini

remove some redundancy in tox.ini

tox.ini cleanup

---

.github/workflows/test_release.yml

* lint and test concurrently
* only run tests on push when source or test change

lint and test concurrently

---

scripts/release_manager.py

A published release will trigger the test and release workflow which will upload a new version of the sdk to PyPi.

releases are published, not draft

---

tests/conftest.py
tox.ini

running slow tests as a default now
make skip slow tests the default behavior
tox

Make skip slow tests the default behavior

---

scripts/release.py

check the number of source lines changed before releasing

check number of source lines changed before releasing

---

.github/workflows/release.yml

release at 9 AM PST

---

tests/conftest.py

docker is not setup if run for the first time
Remove Slow marker in conftest so we dont ignore docker setups if run for the first time

Remove slow marker in conftest

---

.github/workflows/test_release.yml
scripts/release.py

fetch latest tag during release

fetch latest tag during release

---

README.rst

Add SageMaker analytics example

---

README.rst
tests/conftest.py

Allow test to run against different regions

---

src/smexperiments/trial.py
tests/unit/test_trial.py

fix an bug when calling trial.create with trial components

fix: create trial with trial components

---

src/smexperiments/trial.py
tests/unit/test_trial.py

Able to add/remove trail component to Trial via TrailComponentSummary
https://sim.amazon.com/issues/AML-60249

fix: able to add and remove trail component summary

---

src/smexperiments/trial_component.py
tests/integ/test_trial_component.py
tests/unit/test_trial_component.py

Enable Removal of Parameters and Artifacts in TrialComponent
https://sim.amazon.com/issues/AML-71673

Enable Removal of Parameters and Artifacts under TrialComponent update

---

src/smexperiments/experiment.py
src/smexperiments/trial.py
src/smexperiments/trial_component.py
tests/conftest.py
tests/integ/test_experiment.py
tests/integ/test_trial.py
tests/integ/test_trial_component.py
tests/unit/test_experiment.py
tests/unit/test_trial.py
tests/unit/test_trial_component.py

- Allow Passing Tags in E/T/TC Create methods
- https://sim.amazon.com/issues/AML-71615
- Unit tests & integration tests

Allow Passing Tags in E/T/TC Create methods

---

src/smexperiments/trial_component.py
tests/conftest.py
tests/integ/test_trial_component.py
tests/unit/test_trial_component.py

Add disassociate param to trial component delete method 
https://sim.amazon.com/issues/AML-70474

Add disassociate param to trial component delete method 

---

tests/integ/test_trial_component.py

remove extra integ test during merge.

remove extra integ test

---

src/smexperiments/experiment.py
tests/conftest.py
tests/integ/test_experiment.py
tests/unit/test_experiment.py

add delete_all(action="--force") under experiment to delete the experiment and associated trials, trial components.
https://sim.amazon.com/issues/AML-70471
https://sim.amazon.com/issues/AML-73053

add delete_all(action="--force") method under experiment

---

src/smexperiments/experiment.py

explain delete/disassociate behavior 
https://sim.amazon.com/issues/AML-70475

explain delete/disassociate behavior 

---

src/smexperiments/trial_component.py

doc typo fix in trial_component attributes documentation

---

scripts/version.py
src/smexperiments/_base_types.py
src/smexperiments/_boto_functions.py
src/smexperiments/experiment.py
src/smexperiments/metrics.py
src/smexperiments/tracker.py
src/smexperiments/training_job.py
src/smexperiments/trial.py
src/smexperiments/trial_component.py
tests/conftest.py
tests/integ/test_training_job.py
tests/unit/test_base_types.py
tests/unit/test_experiment.py
tests/unit/test_list_trial_components_from_trial.py
tests/unit/test_trial.py
tests/unit/test_trial_component.py

add delete_all method to Trial
also black format
https://github.com/aws/sagemaker-experiments/issues/74

feature: add delete_all method to Trial

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test_release.yml
CONTRIBUTING.md
README.rst
docs/links.rst
scripts/release.py

switch primary branch from master to main

switch primary branch from master to main

---

tests/conftest.py

revert use of CMH in test setup

revert use of CMH in test setup

---

README.rst

add docker-based test instructions

add docker-based test instructions

---

tests/conftest.py

add sleep in integ test for consistent results

add sleep in integ test for consistent results

---

src/smexperiments/tracker.py

add note to methods that call restricted API CreateArtifact

add note to methods that call restricted API CreateArtifact

---

src/smexperiments/tracker.py
tests/unit/test_tracker.py

handle max input/output artifacts on Tc

handle max input/output artifacts on TC

---

src/smexperiments/tracker.py
tests/integ/test_tracker.py

https://sim.amazon.com/issues/AML-92146
log all files in a directory
tox -e py37 -- tests/integ
tox -e py37 -- tests/unit

Log all files in a directory

---

src/smexperiments/tracker.py
src/smexperiments/trial_component.py
tests/integ/test_tracker.py
tests/integ/test_trial_component.py
tests/unit/test_trial_component.py

List trials under TrialComponent class
https://sim.amazon.com/issues/AML-80452
tox -e py38 --  tests/integ/test_trial_component.py
tox -e py38 --  tests/unit/test_trial_component.py

list trials under trial component

---

tox.ini

collect-tests is used for some IDE test integrations
```
--- aws/sagemaker-experiments ‹main* M› » tox -e collect-tests                                                                                                                                        1 ↵
GLOB sdist-make: /Users/danabens/workplace/github/aws/sagemaker-experiments/setup.py
collect-tests create: /Users/danabens/workplace/github/aws/sagemaker-experiments/.tox/collect-tests
collect-tests installdeps: boto3 >= 1.12.8, python-dateutil, pytest, pytest-cov, docker
collect-tests inst: /Users/danabens/workplace/github/aws/sagemaker-experiments/.tox/.tmp/package/1/sagemaker-experiments-0.1.26.dev7+g9363166.d20210122.zip
collect-tests installed: apipkg==1.5,appdirs==1.4.4,atomicwrites==1.4.0,attrs==20.3.0,boto3==1.16.59,botocore==1 …
```

add collect tests tox env

---

tests/helpers.py
tests/integ/test_tracker.py

add wait for trial component to be created to improve test reliability

add wait for trial component to be created to improve test reliability

---

src/smexperiments/tracker.py
tests/unit/test_tracker.py

enable log of precision recall graphs

enable log of precision recall graphs

---

tests/unit/artifact_schemas/confusion_matrix_v0.json

add confusion matrix json schema

add confusion matrix json schema

---

src/smexperiments/tracker.py
tests/unit/test_tracker.py

add log confusion matrix method

feature: add log confusion matrix

---

src/smexperiments/tracker.py

doc: clarify receiver operating characteristic curve doc

doc: clarify receiver operating characteristic curve doc

---

src/smexperiments/tracker.py

minor updates to tracker documentation

doc: update graph artifact documentation

---

src/smexperiments/tracker.py

add a note directing to the main SDK to avoid confusion

doc: add note regarding enable_sagemaker_metrics

---

README.rst

*Issue #, if available:* n/a
*Description of changes:* Use SageMaker default bucket instead of placeholder variable.
*Testing done:* Ran in notebook instance.

Use SageMaker default bucket

---

tests/conftest.py
tests/integ/test_tracker.py
tests/integ/test_trial.py

retry some integration tests that have been inconsistent recently

retry association tests

---

docs/conf.py
tests/helpers.py

black format fix

---

src/smexperiments/tracker.py

Fix several minor documentation errors in `Tracker`.

minor documentation fixes in Tracker

---

.github/workflows/test_release.yml
setup.py
tests/unit/test_utils.py
tox.ini

*Issue #, if available:* (internal sim and ticket)
*Description of changes:* add support for python 3.10 and 3.11 for compatibility with recent changes in DLC containers
*Testing done:* unit tests passing for all environments

add support for python 3.10 and 3.11

---

.github/workflows/test_release.yml

*Issue #, if available:* internal ticket
*Description of changes:* fix github actions workflow
*Testing done:* verify PR run pass
>the uses attribute must be a path, a Docker image, or owner/repo@ref

update action workflow for new python versions

---

.github/workflows/test_release.yml

*Issue #, if available:* internal ticket
*Description of changes:* address workflow failure i.e. https://github.com/aws/sagemaker-experiments/actions/runs/4308935186

add version numbers to uses statements

---

.github/workflows/test_release.yml
tests/integ/test_tracker.py
tests/unit/test_base_types.py
tests/unit/test_tracker.py
tests/unit/test_utils.py

*Issue #, if available:* internal ticket
*Description of changes:* 
* resolve action not running due to syntax error
* line spacing a result of black format to satisfy linter `tox -e black-format`
*Testing done:* action run and passes for this PR

add version number to checkout uses

---

scripts/release.py

*Issue #, if available:* none
*Description of changes:* improves maintainability of repo - easier to deploy maintenance type changes, which aren't necessarily to source files
*Testing done:* PR action worklfow

deploy new version for non source changes

---

tests/conftest.py

*Issue #, if available:* https://github.com/aws/sagemaker-experiments/issues/183
*Description of changes:* Remove unused service principals
*Testing done:* tox tests/unit

fix: fix the issue allowing unused service principals

---

src/smexperiments/_environment.py
tests/unit/test_environment.py

*Issue #, if available:* 188
*Description of changes:* fix the trial-component loading issue for jobs with mix-case name
*Testing done:* unit tests

fix: fix the trial-component loading issue for jobs with mix-case name

---

docs/conf.py

*Issue #, if available:* broken doc build
*Description of changes:* fix doc build
*Testing done:* `tox -e docs`

fix doc build

---

.github/workflows/test_release.yml

*Issue #, if available:* fix release task failure 
example failures: https://github.com/aws/sagemaker-experiments/actions/runs/4917647650/jobs/8783470192
*Description of changes:* fetch all tags and branches on cehckout for release task
*Testing done:* suggested fix from https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

fix release task
