- tests/integ-jobs/test_track_from_training_job.py
these tests are consistently failing and slow. there is a sim to improve them, skip them for now.
> skip auto create tests

- src/smexperiments/api_types.py
- tests/unit/test_api_types.py
add __str__ method to TrialComponentParameterValue type
```
============================================================================================ 88 passed in 1.49s ============================================================================================
py36 run-test: commands[1] | coverage report --fail-under=80
Name                                                                     Stmts   Miss  Cover
--------------------------------------------------------------------------------------------
.tox/py36/lib/python3.6/site-packages/smexperiments/__init__.py              2      0   100%
.tox/py36/lib/python3.6/site-packages/smexperiments/_base_types.py          69      4    94%
.tox/py36/lib/python3.6/site-packages/smexperiments/_boto_functions.py      34      0   100% …
```
> add __str__ method to TrialComponentParameterValue type

- README.rst
- src/smexperiments/api_types.py
- tests/unit/test_api_types.py
- tox.ini
add codecov integration to visualize code coverage
example from fork: https://codecov.io/gh/danabens/sagemaker-experiments
similar to what main python sdk has: https://codecov.io/gh/aws/sagemaker-python-sdk
> add codecov integration

- .gitignore
- README.rst
- docs/Makefile
- docs/conf.py
- docs/experiment.rst
- docs/index.rst
- docs/metrics.rst
- docs/tracker.rst
- docs/trial.rst
- docs/trial_component.rst
- tox.ini
add documentation generation with sphinx
```
╰ tox -e docs
GLOB sdist-make: /Users/danabens/workplace/github/sagemaker-experiments/setup.py
docs inst-nodeps: /Users/danabens/workplace/github/sagemaker-experiments/.tox/.tmp/package/1/sagemaker-experiments-0.1.4.zip
docs installed: alabaster==0.7.12,apipkg==1.5,atomicwrites==1.3.0,attrs==19.3.0,Babel==2.8.0,boto3==1.11.3,botocore==1.14.3,certifi==2019.11.28,chardet==3.0.4,commonmark==0.9.1,coverage==5.0.3,docutils==0.15.2,entrypoints==0.3,execnet==1.7.1,filelock==3.0.12,flake8==3.7.9,idna==2.8,imagesize==1.2.0,importlib-metadata==0.23,Jinja2==2.10.3,jmespath==0.9.4,MarkupSafe==1.1.1,mccabe==0.6.1,more-itertools==8.1.0,packaging==20.0,pathlib2==2.3.5,pluggy==0.13.1,py==1.8.1,pycodestyle==2.5.0,pyflakes==2.1.1,Pygments==2.5.2,pyparsing==2.4 …
```
> add documentation generation

- .github/workflows/build_release.yml
- .gitignore
- docs/conf.py
- tests/unit/test_tracker.py
- tox.ini
pull requests do not have access to the main repo's secrets for security and as a result will not be able to run integ tests on pr. instead run integration tests on a push or release.
integ tests are run on push to a fork: https://github.com/danabens/sagemaker-experiments/actions/runs/32374968 
* also only push coverage to codecov on a release rather than each environment build
* also only run integ tests once, instead of for each python version
> run integ tests only when secrets are available

- .github/workflows/build_release.yml
use api token to upload to pypi, upload to test first, use twine directly instead of 3rd party action
see http://pyfound.blogspot.com/2019/07/pypi-now-supports-uploading-via-api.html
> use api token

- .github/workflows/build_publish.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- scripts/release.py
- scripts/release_manager.py
- scripts/release_template.rst
- scripts/subject_parser.py
- scripts/version.py
- tox.ini
Check for new changes to release every weekday at 9 AM. If there are new changes to source a release in GitHub will be created which kicks off the build and publish workflow.  
In order to do manual verification, for the time being the release will be created in draft mode which will not trigger the release to pypi.
example release in fork: https://github.com/danabens/sagemaker-experiments/runs/418194698?check_suite_focus=true
> add release script and workflow

- .github/workflows/test_release.yml
- tox.ini
fix codecov upload
```
 tox -e upload-coverage
GLOB sdist-make: /Users/danabens/workplace/github/sagemaker-experiments/setup.py
upload-coverage recreate: /Users/danabens/workplace/github/sagemaker-experiments/.tox/upload-coverage
upload-coverage installdeps: codecov
upload-coverage inst: /Users/danabens/workplace/github/sagemaker-experiments/.tox/.tmp/package/1/sagemaker-experiments-0.1.6.dev0+gbc19b25.d20200131.zip
upload-coverage installed: apipkg==1.5,atomicwrites==1.3.0,attrs==19.3.0,boto3==1.11.9,botocore==1.14.9,certifi==2019.11.28,chardet==3.0.4,codecov==2.0.15,coverage==5.0.3,docker==4.1.0,docutils==0.15.2,entrypoints==0.3,execnet==1.7.1,filelock==3.0.12,flake8==3.7.9,idna==2.8,importlib-metadata==0.23,jmespath==0.9.4,mccabe==0.6.1,more-itertools==8.2.0,packaging==20.1,pluggy==0 …
```
> fix codecov upload

- .github/workflows/test_release.yml
- scripts/release.py
combine release workflow into main workflow
workflows can't trigger other workflows unfortunately  
>An action in a workflow run can't trigger a new workflow run. For example, if an action pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
> combine release workflow into main workflow

- src/smexperiments/_base_types.py
- tests/unit/test_base_types.py
- Add default sagemaker_boto_client to list classmethods. These can now be called without specifying a client.
- Fix PEP479 Python 3.7 bug - StopIteration now not thrown from list method.
- New unit test
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/master/CONTRIBUTING.md) doc
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/master/CONTRIBUTING.md#committing-your-change)
- [ x] I …
> fix. Add default sagemaker_boto_client to list classmethods.

- scripts/release.py
- scripts/release_manager.py
after creating the release pull to local repo so subsequent workflow steps have the newly created tag
> pull latest tag after creating release

- src/smexperiments/tracker.py
- tests/unit/test_tracker.py
https://github.com/aws/sagemaker-experiments/issues/60
Added metrics writer creation in Tracker.create path.  Since the metric writer is only writing to file (not an API) there is no reason to limit its use to only ```load``` or in a SageMaker context. Ideally, the only difference between load and create should be where the trial component is retrieved from.
unit tests
> feature - create metrics writer in Tracker.create path

- scripts/release.py
convert version to string before concatenation
```
tag = "v" + self._version
TypeError: can only concatenate str (not "Version") to str
```
> convert version to string before concatenation

- README.rst
- setup.py
- src/smexperiments/trial.py
- tests/integ/test_trial.py
- tests/unit/test_trial.py
- tox.ini
> Support ListTrials by trial component name

- src/smexperiments/api_types.py
- src/smexperiments/training_job.py
- tests/conftest.py
- tests/integ/test_track_from_processing_job.py
- tests/integ/test_track_from_training_job.py
- tests/integ/test_training_job.py
- tests/unit/test_training_job.py
> Add search for training job and fix slow tests

- src/smexperiments/metrics.py
We initialize the metrics file writer by lazy initializing a file handle after an initial ```AttributeError``` occurs on the first attempt to log_metric. However the first thing within the ```try``` block was a ```logging.error``` statement which surfaced the exception to the notebook user (causing confusion) even though we expected it and handled it successfully. Removed the error log as we are either raising or handling all exceptions so there is no reason for the error log.
Created a test notebook, loaded modified SDK files, verified error is not logged and metrics are written to file as expected.
There are no other similar error log statements in the repo.
> fix: don't log an error during expected exception in metrics file writer

- src/smexperiments/tracker.py
Add additional information regarding log_metric behavior in documentation to avoid customer confusion.
> add additional notes on log_metric behavior to avoid confusion

- src/smexperiments/experiment.py
- tests/integ/test_experiment.py
- tests/integ/test_trial.py
- tests/integ/test_trial_component.py
- tests/unit/test_experiment.py
1.remove auto generated aws tag in integ test.
2. fix delete_all exception message. 
based on https://stackoverflow.com/questions/1483429/how-to-print-an-exception-in-python, we need to add str() around exception for python 2.5 and earlier.
> remove auto generated aws tag in integ test. fix delete_all exception

- src/smexperiments/experiment.py
SIM: https://sim.amazon.com/issues/AML-78535
1. Fix DisassociateTrialComponent throttling, 
since we already do disassociate and delete trial_component with code tc.delete(force_disassociate=True). So t.remove_trial_component(tc) is not needed.
2. add sleep time under trial and experiment also contain 1s throttle time. add a time.sleep between experiment and trial deletion. 
Based on https://tiny.amazon.com/ftd9gdrx/codeamazpackIronbloba686conf 
Error:
> my_experiment.delete_all(action="--force")
> ---------------------------------------------------------------------------
> ClientError                               Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/smexperiments/experiment.py in delete_all(self, action)
>     261 …
> fix experiment.delete_all() throttle

- .gitignore
- src/smexperiments/metrics.py
- tests/unit/test_metrics.py
log_metric was using binary based buffering that flushed to file after a certain number of bytes were written (~60 lines) instead of new line buffering.
https://docs.python.org/3/library/functions.html#open
> fix metric buffer not flushing on newline

- tests/conftest.py
fix occasional throttling exception and black format
>        # associate the trials with trial components
>        for trial_obj in trial_objs:
>            sagemaker_boto_client.associate_trial_component(
>               TrialName=trial_obj.trial_name, TrialComponentName=trial_component_obj.trial_component_name
>           )
> botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the AssociateTrialComponent operation (reached max retries: 4): Rate exceeded
> fix: integration test throttling of AssociationTrialComponent

- src/smexperiments/tracker.py
- tests/unit/test_tracker.py
Add documentation on `log_metric` limitations due to how it works: sdk writes metrics to file and metrics agent parses metrics in file and adds to SM, if the metrics agent isn't present then metrics won't show up in SM.
> add documentation regarding limitations of log_metric method

- src/smexperiments/tracker.py
- tests/unit/artifact_schemas/precision_recall_curve_v0.json
- tests/unit/test_tracker.py
Add an optional parameter for the no skill line in the `log_precision_recall` method.
> add no skill to P/R curve graph artifact

- src/smexperiments/tracker.py
- tests/unit/test_tracker.py
…ssed
NA
Changed parameter validation for dataframe to `if dataframe is not None:`. Current `if dataframe:` causes the `index of an array is ambiguous...etc` error which was preventing using it to log dfs. 
Added a simple dataframe test. Let me know if more are needed.  The `.to_dict()` method in the conversion should catch most things that aren't dataframes. Maybe consider `isinstance`ing and raising as well? Happy to add it. 
- [ x] I have read the …
> Fix to parameter validation of `tracker.log_table`

- .github/workflows/test_release.yml
- tox.ini
remove unnecessary codecov token
From settings page:
> Note: Token not required for public repositories uploading from Travis, CircleCI, AppVeyor, Azure Pipelines or GitHub Actions.
> remove unneccessary codcov token

- .github/workflows/test_release.yml
- tox.ini
This wasn't actually necessary  or correct - just needed to rotate codecov token and mis-interpreted instructions on codecov settings page ("no-token-needed" only applies when using the official codecov GH action, not when running codecov generically via tox).
> Revert "remove unneccessary codcov token"

- src/smexperiments/tracker.py
Tracker has some confusing behavior around metrics and documentation needs to be updated to reflect it.
> clarify log_metric behavior in Tracker documentation

- README.rst
*Issue #, if available:* https://github.com/aws/amazon-sagemaker-examples/issues/2876
*Description of changes:* Download MNIST dataset from AWS-hosted bucket, instead of from broken third-party URL. Add missing os package import.
*Testing done:* Ran code snippet in SageMaker notebook instance.
> Fix MNIST data location, add os import

- .github/workflows/test_release.yml
This will ensure the build will fail docs fail to generate.
> generate docs during CI

- tests/integ/test_trial.py
fix an issue with failing test by adding logging, increasing retries, separating validation steps
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
def validate():
trial_components = list(trial_obj.list_trial_components())
>       assert 1 == len(trial_components)
E       assert 1 == 0
E        +  where 0 = len([])
tests/integ/test_trial.py:115: AssertionError
----------------------------- Captured stdout call -----------------------------
Retrying assert 0 == 1
+  where 1 = len([TrialComponentSummary(trial_component_name='smexperiments-integ-f3c230a1-0a64-45ae-80c2-c40e9b05fb68',trial_component...ted_by={},last_modified_time=datetime.datetime(2022, 4, 22, 14, 17, 35, 738000, tzinfo=tzlocal()),last_modified_by={})])
Retrying assert 1 == 0
+  where 0 = …
```
> improve logging and retry of trial add/remove TC test

- src/smexperiments/tracker.py
- tests/unit/test_tracker.py
*Issue #, if available:* [126](https://github.com/aws/sagemaker-experiments/issues/126)
*Description of changes:* log a warning and skip numbers that aren't serializable (nan, inf, -inf) when logging a metric or parameter
*Testing done:* unit tests
> skip invalid numbers when logging a metric or parameter

- src/smexperiments/tracker.py
*Description of changes:* update documentation for three tracker apis (log_precision_recall, log_roc_curve, log_confusion_matrix) to show that their artifacts can be viewed in the Trial Component UI
> doc: view ROC, PR, and confusion matrix in Trial Component UI

- src/smexperiments/_utils.py
*Description of changes:* Increase the length of the suffix for auto-generated entities by increasing the time resolution from seconds to microseconds (adding 6 characters to the suffix).
*Testing done:* Unit tests.
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/main/CONTRIBUTING.md) doc
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/main/CONTRIBUTING.md#committing-your-change)
- [x ] I have …
> change name suffix resolution to account for sub-second api calls

- .github/workflows/test_release.yml
sign step inconsistent, requires secret updates. twine has alternatives which we will adopt later.
> remove failing sign step

- scripts/release.py
- src/smexperiments/_environment.py
- tests/unit/test_environment.py
*Issue #, if available:* internal customer ticket
*Description of changes:* near term mitigation for arn casing changes on backend which are currently causing `Tracker.load` to fail when a training job has upper case.
*Testing done:* locally `tox -e p38 -- -m 'not docker'
```
❯ tox -e py38 -- -m 'not docker'
GLOB sdist-make: /Users/danabens/workplace/github/aws/sagemaker-experiments/setup.py
py38 inst-nodeps: /Users/danabens/workplace/github/aws/sagemaker-experiments/.tox/.tmp/package/1/sagemaker-experiments-0.1.40.dev3+g954d731.zip
py38 installed: atomicwrites==1.4.1,attrs==22.1.0,boto3==1.26.16,botocore==1.29.16,certifi==2022.9.24,charset-normalizer==2.1.1,coverage==6.5.0,distlib==0.3.6,docker==6.0.1,exceptiongroup==1.0.4,execnet==1.9.0,filelock==3.8.0,flake8==6.0.0,idna==3.4,importlib-m …
```
> lowercase source arn before listing trial components

- setup.py
Changing the `sklearn` dep to `scikit-learn` following the advisory published at https://github.com/scikit-learn/sklearn-pypi-package.
Unit tests for Python3.7 and Python 3.8.
```
tox tests/unit                                                             ~/workplace/sagemaker-experiments
GLOB sdist-make: /workplace/ksiman/sagemaker-experiments/setup.py
py36 create: /workplace/ksiman/sagemaker-experiments/.tox/py36
ERROR: InterpreterNotFound: python3.6
py37 create: /workplace/ksiman/sagemaker-experiments/.tox/py37
py37 installdeps: boto3 >= 1.12.8, python-dateutil, pytest, pytest-cov, docker, scikit-learn==0.24.2
py37 inst: /workplace/ksiman/sagemaker-experiments/.tox/.tmp/package/1/sagemaker-experiments-0.1.dev140+gbca8812. …
```
> [fix] Update deprecated sklearn dep

- .github/workflows/test_release.yml
- scripts/release.py
>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-python@v1 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
also set exit code to 0 when nothing to release
> upgrade action versions

- scripts/release.py
*Issue #, if available:* fix `No names found, cannot describe anything.` error during release action i.e. https://github.com/aws/sagemaker-experiments/actions/runs/4895788454/jobs/8742195201
*Description of changes:* call fetch --all to retrieve tags
> fix: fetch all during release

- README.rst
*Issue #, if available:* no issue
*Description of changes:* release task is currently failing due to a syntax error in the README.rst see https://github.com/aws/sagemaker-experiments/actions/runs/4994718175/jobs/8946259829
*Testing done:* test release
> fix readme description syntax error causing release action to fail
